### ISSUE TITLE
False alarm snapshot

### ISSUE THREAD

**Issue by siriwatknp** [argos-ci/argos#901] opened 2023-06-22 05:06 UTC
**PR**: https://github.com/mui/material-ui/pull/37515
**Argos**: https://app.argos-ci.com/mui/material-ui/builds/14401/50329248

The code for this component does not change but Argos throws the diff in the PR. Also, I could not detect any pixel change in the Argos console:

<img width="1439" alt="image" src="https://github.com/argos-ci/argos/assets/18292247/06be683a-0f47-45cb-b15b-2637ffa42044">

We have been experiencing this issues multiple times and we would like to know if we are doing something wrong or it is from Argos side.

**Comment by jsfez** [comment] 2023-06-22 06:30
Hello @siriwatknp,

Thank you for bringing this to our attention. This certainly is an unusual issue and it is indeed concerning.

Firstly, I can confirm that the two images are identical. I've run them through our diff algorithm, and it agrees - there are no discernible differences between them.

This warrants a more in-depth investigation to determine the root cause. Please bear with us as we look into this matter. Rest assured, I'll keep you updated with any significant findings or progress we make in resolving this issue.

Thank you again for your patience and understanding.

**Comment by siriwatknp** [comment] 2023-06-22 06:39
> Hello @siriwatknp,
> 
> Thank you for bringing this to our attention. This certainly is an unusual issue and it is indeed concerning.
> 
> Firstly, I can confirm that the two images are identical. I've run them through our diff algorithm, and it agrees - there are no discernible differences between them.
> 
> This warrants a more in-depth investigation to determine the root cause. Please bear with us as we look into this matter. Rest assured, I'll keep you updated with any significant findings or progress we make in resolving this issue.
> 
> Thank you again for your patience and understanding.

Thanks for the fast response!

**Comment by gregberge** [comment] 2023-06-23 07:52
Actually I spotted the diff:

![image](https://github.com/argos-ci/argos/assets/266302/4039019c-a771-4ee2-be4a-af7980f2fbef)

Since the screenshot is small 1px is sufficient to trigger a change. The problem is browser glitches. It happens, we should solve it in future. No bug, just a feature to solve glitches detection :)

**Closed by gregberge** 2023-06-23 07:52 UTC
