### ISSUE TITLE
Support subsequent uploads to the same Argos build

### ISSUE THREAD

**Issue by cherniavskii** [argos-ci/argos#457] opened 2022-08-10 10:22 UTC
As a user,
I expect subsequent uploads to the same Argos build to be reflected Argos build.

### Motivation

Sometimes we have flaky screenshots and therefore false negatives in Argos.
To make argos pass, we have to push new commit to the branch (or rebase), which restarts the whole CI pipeline.
It would be great if we could only restart a single step in the pipeline that creates screenshots and uploads them to argos.

### Detail

In MUI X we use Argos as part of our CI pipeline.
We use argos-cli to upload screenshots, but I've noticed that subsequent uploads are ignored by Argos build.
Specifically, upload date stays the same ("2 hours ago" in the screenshot below, even though there were screenshots uploaded just few minutes ago) and failed screenshots list stays the same:
<img width="1035" alt="Screenshot 2022-08-10 at 12 15 21" src="https://user-images.githubusercontent.com/13808724/183877862-00a1bf35-f141-4f39-acdb-3078b0d35268.png">

Link to argos build: https://app.argos-ci.com/mui/mui-x/builds/2942
Link to the latest CI step that triggered argos upload: https://app.circleci.com/pipelines/github/mui/mui-x/21840/workflows/a969b05b-44b7-463c-83ee-61fdb80f34cb/jobs/126164

**Comment by gregberge** [comment] 2022-08-12 16:35
Hi @cherniavskii, the problem is that you are not using a valid `externalId` but she CIRCLE_SHA1. The external ID must be the ID of the CI Build: `CIRCLE_BUILD_NUM` (https://circleci.com/docs/env-vars).

The line to change is here:

https://github.com/mui/material-ui/blob/7b945c739335dfe741f068d1199f16d3155e3a5e/scripts/pushArgos.js#L48

Soon a new build system will be in place but the problem would remain the same if you don't make this change.

**Closed by gregberge** 2022-08-12 16:35 UTC

**Comment by cherniavskii** [comment] 2022-08-15 10:00
Hey @gregberge 
Thanks for looking into it!
Indeed, using `CIRCLE_BUILD_NUM` totally makes sense. I'll try it out.

Just to clarify, subsequent uploads with the same `externalId` are ignored by Argos, right?

**Comment by gregberge** [comment] 2022-09-06 07:47
@cherniavskii all doc here: https://docs.argos-ci.com/argos-cli#parallel-test-suites
